/**
 * GENERATED CODE — do not edit by hand.
 *
 * <p>
 * Every class in this package is generated by the
 * {@code openapi-generator-maven-plugin} from {@code swagger/eaton.yaml} using
 * the custom templates in {@code swagger/templates}. To change a model, edit
 * the schema and regenerate:
 *
 * <pre>
 * mvn -Pgenerate-models process-sources
 * </pre>
 *
 * <p>
 * Hand edits are lost on the next regeneration (the {@code generate-models}
 * profile cleans this directory first). CI verifies that the committed sources
 * match the schema.
 */
package cloud.cholewa.gateway.eaton.model;
